# 작업형1 모의문제2
- data : members.csv

## 문제4
- 주어진 데이터에서 자료형(type)이 object인 컬럼은 삭제하고, 결측치는 0으로 대체한다.
- 행 단위로 합한 다음 그 값이 3000보다 큰 값의 데이터 수를 구하시오
('age', 'f1', 'f2', 'f5', 'views'의 각 행별 합)

In [ ]:
# your code
# import pandas as pd
# import numpy as np

# df = pd.read_csv("members.csv")

# 자료형이 object인 열 삭제 & 결측치는 0으로 대체
# 전체 칼럼 타입 조회
# print(df.info())
# object 컬럼인지 확인 => select_dtypes(include='')
# df.select_dtypes(include='object')
# 해당 칼럼명만 조회 => .columns
# cols = df.select_dtypes(include='object').columns
# 해당 카럼 삭제 => drop
# df = df.drop(cols, axis=1)
# 만약 object 칼럼이 아닌 것만 선택하려면 => exclude
# df.select_dtypes(exclude = 'object')

#결측치는 0으로
# print(df.isnull().sum())
# df = df.fillna(0)
# print(df.isnull().sum())

#행단위로 합
# df.sum() # 이거는 열단위호 합
# 따라서 행, 열 위치 교체
# df = df.T
# 그리고 나서 sum 사용
# print(sum(df.sum() > 3000))

age      0
f1       0
f2       0
f5       0
views    0
dtype: int64
73

## 문제5
- 데이터에서 IQR을 활용해 views 컬럼의 이상치를 찾고, 이상치 데이터의 수를 구하시오

In [ ]:
# your code
# IQR = 3사분위q3 - 1사분위q1

df = pd.read_csv("members.csv")

# 3사분위값
q3 = df['views'].quantile(0.75)
# 1사분위값
q1 = df['views'].quantile(0.25)
IQR = q3-q1
print(IQR)

#이상치
lower = q1 - 1.5*IQR
upper = q3 + 1.5*IQR

# 데이터수
cnt1 = sum(df['views'] < lower)
cnt2 = sum(df['views'] > upper)

print(cnt1 + cnt2)

5113.5
4

## 문제6
- 'age' 컬럼의 이상치(소수점 나이와 음수나이, 0포함)를 제거하고
- 제거 전 후의 views 컬럼 표준편차를 더하시오 (최종 결과 값은 소수 둘째자리까지 출력, 셋째자리에서 반올림)

In [ ]:
# your code
df = pd.read_csv("members.csv")

# 제거전 표준편차
r1 = df['views'].std()

# 0이하 나이 제거
cond = df['age'] <= 0
df = df[~cond]

# 소수점 나이 제거 -> # 소수점 판단 ? 반올림한 값과 age가 다르면 소수점이라 판단
cond = df['age'] != round(df['age'])
df = df[~cond]


r2 = df['views'].std()

# 소수 둘째자리 까지 + 반올림
print(round(r1 + r2, 2))

8420.69

# 풀이

## 문제4
- 주어진 데이터에서 자료형(type)이 object인 컬럼은 삭제하고, 결측치는 0으로 대체한다.
- 행 단위로 합한 다음 그 값이 3000보다 큰 값의 데이터 수를 구하시오
('age', 'f1', 'f2', 'f5', 'views'의 각 행별 합)

In [ ]:
# 풀이
import pandas as pd
df = pd.read_csv("members.csv")

# cols = df.select_dtypes(include='object').columns
# cols
# df = df.drop(cols, axis=1)
# df.head()

cols = df.select_dtypes(exclude='object').columns
cols
df = df[cols]
df.head()

df = df.fillna(0)
df = df.T
df.head()
print(sum(df.sum() > 3000))

73

## 문제5
- 데이터에서 IQR을 활용해 views 컬럼의 이상치를 찾고, 이상치 데이터의 수를 구하시오

In [ ]:
# 풀이
import pandas as pd
df = pd.read_csv("members.csv")

q3 = df['views'].quantile(.75)
q1 = df['views'].quantile(.25)

IQR = q3 - q1
# print(IQR)

line1 = q1 - 1.5 * IQR
line2 = q3 + 1.5 * IQR


print(sum(df['views'] < line1) + sum(df['views'] > line2))

4

## 문제6
- 'age' 컬럼의 이상치(소수점 나이와 음수나이, 0포함)를 제거하고
- 제거 전 후의 views 컬럼 표준편차를 더하시오 (최종 결과 값은 소수 둘째자리까지 출력, 셋째자리에서 반올림)

In [ ]:
# 풀이
import pandas as pd
df = pd.read_csv("members.csv")

r1 = df['views'].std()

cond = df['age'] <= 0
# print(df.shape)
df = df[~cond]
# print(df.shape)

# print(df.shape)
cond = df['age'] == round(df['age'],0)
df = df[cond]
# print(df.shape)

r2 = df['views'].std()

print(round(r1 + r2, 2))

8420.69